language: cpp

os: linux

dist: trusty

sudo: required

addons:
  apt:
    package:
    - cmake

before_script: chmod +x ./ci_build.sh
script: ./ci_build.sh

notifications:
  email:
    - rangercyh@qq.com
